// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// import { initializeApp } from "firebase/app";
// import { getAnalytics } from "firebase/analytics";
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4V1z8yxm52ynBvoGOmZiAx-VgRGxyTQI',
    appId: '1:503489886626:web:bb0938ac7dff7aeec55afb',
    messagingSenderId: '503489886626',
    projectId: 'notesapp-c3eb4',
    authDomain: 'notesapp-c3eb4.firebaseapp.com',
    storageBucket: 'notesapp-c3eb4.appspot.com',
    measurementId: "G-105C97MF63",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa-UHZBcdvewikjyG5HQ9Us8JZrfMjcbg',
    appId: '1:503489886626:android:926888d8165ceff6c55afb',
    messagingSenderId: '503489886626',
    projectId: 'notesapp-c3eb4',
    storageBucket: 'notesapp-c3eb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs39NrTCZbThKooy0eVN4km49kGojNeE8',
    appId: '1:503489886626:ios:ed17cf9c8b418c41c55afb',
    messagingSenderId: '503489886626',
    projectId: 'notesapp-c3eb4',
    storageBucket: 'notesapp-c3eb4.appspot.com',
    iosClientId: '503489886626-a2b9c3aqvi1k3vekk8stqhj0bqec54no.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs39NrTCZbThKooy0eVN4km49kGojNeE8',
    appId: '1:503489886626:ios:ed17cf9c8b418c41c55afb',
    messagingSenderId: '503489886626',
    projectId: 'notesapp-c3eb4',
    storageBucket: 'notesapp-c3eb4.appspot.com',
    iosClientId: '503489886626-a2b9c3aqvi1k3vekk8stqhj0bqec54no.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );



}
